ikaros:
  env: ${IKAROS_ENV:pro}
  log-level: ${IKAROS_LOG_LEVEL:INFO}
  server-port: ${IKAROS_SERVER_PORT:9090}
  qbittorrent-base-url: ${IKAROS_QB_URL:http://192.168.2.135:9091/api/v2/}

server:
  port: ${ikaros.server-port}
  shutdown: graceful
  forward-headers-strategy: native
  compression:
    enabled: true
  servlet:
    context-path: /

spring:
  profiles:
    active: ${ikaros.env}

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

  datasource:
    type: com.zaxxer.hikari.HikariDataSource

    # H2 database configuration.
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./db/ikaros;AUTO_SERVER=TRUE
    username: admin
    password: 123456

    #  Add MariaDB database configuration.

  h2:
    console:
      settings:
        web-allow-others: false
      path: /h2-console
      enabled: false
  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
    show-sql: false
    open-in-view: false

  servlet:
    multipart:
      max-file-size: 10240MB
      max-request-size: 10240MB

  thymeleaf:
    cache: true

  flyway:
    locations: migration


logging:
  file:
    name: ./logs/ikaros.log
  level:
    run.ikaros.server: ${ikaros.log-level}
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: INFO
    org.hibernate.type.descriptor.sql.BasicExtractor: INFO
    org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration: OFF
