ikaros:
  external-url: "http://${server.address:localhost}:${server.port}"

server:
  port: 50000
  compression:
    enabled: true
  error:
    whitelabel:
        enabled: false
spring:
  output:
    ansi:
      enabled: detect
  codec:
    max-in-memory-size: 10MB
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${IKAROS_DB_URL:localhost:55432}/${IKAROS_DB_NAME:ikaros}
    username: ${IKAROS_DB_USERNAME:ikaros}
    password: ${IKAROS_DB_PASSWORD:ikaros}
  flyway:
    locations: classpath:migration
    enabled: true
    encoding: UTF-8
    sql-migration-separator: __
    clean-disabled: true
    table: flyway_schema_history


springdoc:
  api-docs:
    enabled: false

logging:
  file:
    name: ./logs/ikaros.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      total-size-cap: 1GB
      max-history: 2
